local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', builtin.find_files, { })
vim.keymap.set('n', '<leader>ps', function()
	builtin.grep_string({search = vim.fn.input("Grep > ")})
end)
vim.keymap.set("n", "<leader>out", function()
  require("telescope.builtin").lsp_document_symbols()
end, { desc = "Document symbols" })
